<?php

namespace Database\Seeders;

use App\Models\AbsenSiswa;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;


class AbsenSiswaTable extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        AbsenSiswa::truncate();

        DB::statement('ALTER TABLE users AUTO_INCREMENT = 1');

        DB::table('absen_siswa')->insert([
            //Evan Septya Utama
            [
                'tanggal_absen' => Carbon::parse('2022-09-05'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Hadir',
                'siswa_id' => 2,
                'kelas_id' => 1,
                'tahun_pelajaran_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2022-10-03'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Hadir',
                'siswa_id' => 2,
                'kelas_id' => 2,
                'tahun_pelajaran_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2022-11-07'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Hadir',
                'siswa_id' => 2,
                'kelas_id' => 1,
                'tahun_pelajaran_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2023-02-06'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Hadir',
                'siswa_id' => 2,
                'kelas_id' => 2,
                'tahun_pelajaran_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2023-03-06'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Hadir',
                'siswa_id' => 2,
                'kelas_id' => 1,
                'tahun_pelajaran_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2023-04-03'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Hadir',
                'siswa_id' => 2,
                'kelas_id' => 2,
                'tahun_pelajaran_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Rinaldo
            [
                'tanggal_absen' => Carbon::parse('2022-09-05'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Hadir',
                'siswa_id' => 3,
                'kelas_id' => 1,
                'tahun_pelajaran_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2022-10-03'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Sakit',
                'siswa_id' => 3,
                'kelas_id' => 2,
                'tahun_pelajaran_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2022-11-07'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Sakit',
                'siswa_id' => 3,
                'kelas_id' => 1,
                'tahun_pelajaran_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2023-02-06'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Hadir',
                'siswa_id' => 3,
                'kelas_id' => 2,
                'tahun_pelajaran_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2023-03-06'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Hadir',
                'siswa_id' => 3,
                'kelas_id' => 1,
                'tahun_pelajaran_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2023-04-03'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Hadir',
                'siswa_id' => 3,
                'kelas_id' => 2,
                'tahun_pelajaran_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Johan
            [
                'tanggal_absen' => Carbon::parse('2022-09-05'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Izin',
                'siswa_id' => 4,
                'kelas_id' => 1,
                'tahun_pelajaran_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2022-10-03'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Hadir',
                'siswa_id' => 4,
                'kelas_id' => 2,
                'tahun_pelajaran_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2022-11-07'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Hadir',
                'siswa_id' => 4,
                'kelas_id' => 1,
                'tahun_pelajaran_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2023-02-06'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Izin',
                'siswa_id' => 4,
                'kelas_id' => 2,
                'tahun_pelajaran_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2023-03-06'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Sakit',
                'siswa_id' => 4,
                'kelas_id' => 1,
                'tahun_pelajaran_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2023-04-03'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Hadir',
                'siswa_id' => 4,
                'kelas_id' => 2,
                'tahun_pelajaran_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Ciu Liu Kang 
            [
                'tanggal_absen' => Carbon::parse('2022-09-05'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Hadir',
                'siswa_id' => 5,
                'kelas_id' => 1,
                'tahun_pelajaran_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2022-10-03'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Alpha',
                'siswa_id' => 5,
                'kelas_id' => 2,
                'tahun_pelajaran_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2022-11-07'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Sakit',
                'siswa_id' => 5,
                'kelas_id' => 1,
                'tahun_pelajaran_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2023-02-06'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Hadir',
                'siswa_id' => 5,
                'kelas_id' => 2,
                'tahun_pelajaran_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2023-03-06'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Hadir',
                'siswa_id' => 5,
                'kelas_id' => 1,
                'tahun_pelajaran_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2023-04-03'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Izin',
                'siswa_id' => 5,
                'kelas_id' => 2,
                'tahun_pelajaran_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Utama
           [
                'tanggal_absen' => Carbon::parse('2022-09-05'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Sakit',
                'siswa_id' => 6,
                'kelas_id' => 1,
                'tahun_pelajaran_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2022-10-03'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Sakit',
                'siswa_id' => 6,
                'kelas_id' => 2,
                'tahun_pelajaran_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2022-11-07'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Alpha',
                'siswa_id' => 6,
                'kelas_id' => 1,
                'tahun_pelajaran_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2023-02-06'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Hadir',
                'siswa_id' => 6,
                'kelas_id' => 2,
                'tahun_pelajaran_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2023-03-06'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Hadir',
                'siswa_id' => 6,
                'kelas_id' => 1,
                'tahun_pelajaran_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2023-04-03'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Hadir',
                'siswa_id' => 6,
                'kelas_id' => 2,
                'tahun_pelajaran_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Titis
            [
                'tanggal_absen' => Carbon::parse('2022-09-05'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Hadir',
                'siswa_id' => 7,
                'kelas_id' => 1,
                'tahun_pelajaran_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2022-10-03'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Alpha',
                'siswa_id' => 7,
                'kelas_id' => 2,
                'tahun_pelajaran_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2022-11-07'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Hadir',
                'siswa_id' => 7,
                'kelas_id' => 1,
                'tahun_pelajaran_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2023-02-06'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Hadir',
                'siswa_id' => 7,
                'kelas_id' => 2,
                'tahun_pelajaran_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2023-03-06'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Sakit',
                'siswa_id' => 7,
                'kelas_id' => 1,
                'tahun_pelajaran_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal_absen' => Carbon::parse('2023-04-03'),
                'waktu_mulai' => Carbon::createFromTime(7, 10),
                'waktu_selesai' => Carbon::createFromTime(12, 35),
                'keterangan' => 'Hadir',
                'siswa_id' => 7,
                'kelas_id' => 2,
                'tahun_pelajaran_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
