<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class PengajarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('pengajars')->insert([
            [
                'id' => 1,
                'nip_pengajar' => 1232,
                'nama_pengajar' => 'Rolando',
                'foto_pengajar' => 'foto_pengajar.png',
                'no_telp_pengajar'=>'08121312',
                'jenis_kelamin_pengajar' => 'Laki-Laki',
                'alamat_pengajar' => 'Jl. Anggur Merah 2, No.27, Bengalon Utara, Kutai Timur, Kalimantan Timur',
                'tempat_lahir_pengajar' => 'Bangalon',
                'ttl_pengajar' => '1990-01-01',
                'jabatan_pengajar' => 'Guru Olahraga',
                'agama_pengajar' => 'Protestan',
                'suku_pengajar' => 'Dayak',
                'rt_rw_pengajar' => '009',
                'desa_kelurahan_pengajar' => 'Teluk Lingga',
                'kecamatan_kota_pengajar' => 'Kutai Timur',
                'kode_pos_pengajar' => 12312,
            ],
            [
                'id' => 2,
                'nip_pengajar' => 1232,
                'nama_pengajar' => 'Jeremy Teti',
                'foto_pengajar' => 'foto_pengajar.png',
                'no_telp_pengajar'=>'08121312',
                'jenis_kelamin_pengajar' => 'Laki-Laki',
                'alamat_pengajar' => 'Jl. Ronda 2, No.27, Jakarta Utara, Kutai Timur, Kalimantan Timur',
                'tempat_lahir_pengajar' => 'Bangalon',
                'ttl_pengajar' => '1990-01-01',
                'jabatan_pengajar' => 'Guru Olahraga',
                'agama_pengajar' => 'Protestan',
                'suku_pengajar' => 'Dayak',
                'rt_rw_pengajar' => '009',
                'desa_kelurahan_pengajar' => 'Teluk Lingga',
                'kecamatan_kota_pengajar' => 'Kutai Timur',
                'kode_pos_pengajar' => 4212,
            ],
            [
                'id' => 3,
                'nip_pengajar' => 12366,
                'nama_pengajar' => 'Rini',
                'foto_pengajar' => 'foto_pengajar.png',
                'no_telp_pengajar'=>'08121312',
                'jenis_kelamin_pengajar' => 'Laki-Laki',
                'alamat_pengajar' => 'Jl. Anggur Merah 2, No.27, Bengalon Utara, Kutai Timur, Kalimantan Timur',
                'tempat_lahir_pengajar' => 'Bangalon',
                'ttl_pengajar' => '1990-01-01',
                'jabatan_pengajar' => 'Guru Olahraga',
                'agama_pengajar' => 'Protestan',
                'suku_pengajar' => 'Dayak',
                'rt_rw_pengajar' => '009',
                'desa_kelurahan_pengajar' => 'Teluk Lingga',
                'kecamatan_kota_pengajar' => 'Kutai Timur',
                'kode_pos_pengajar' => 4332,
            ],
            [
                'id' => 4,
                'nip_pengajar' => 43211,
                'nama_pengajar' => 'Ronal',
                'foto_pengajar' => 'foto_pengajar.png',
                'no_telp_pengajar'=>'08121312',
                'jenis_kelamin_pengajar' => 'Laki-Laki',
                'alamat_pengajar' => 'Jl. Anggur Merah 2, No.27, Bengalon Utara, Kutai Timur, Kalimantan Timur',
                'tempat_lahir_pengajar' => 'Bangalon',
                'ttl_pengajar' => '1990-01-01',
                'jabatan_pengajar' => 'Guru Olahraga',
                'agama_pengajar' => 'Protestan',
                'suku_pengajar' => 'Dayak',
                'rt_rw_pengajar' => '009',
                'desa_kelurahan_pengajar' => 'Teluk Lingga',
                'kecamatan_kota_pengajar' => 'Kutai Timur',
                'kode_pos_pengajar' => 42352,
            ],
            [
                'id' => 5,
                'nip_pengajar' => 6543,
                'nama_pengajar' => 'Joni',
                'foto_pengajar' => 'foto_pengajar.png',
                'no_telp_pengajar'=>'08121312',
                'jenis_kelamin_pengajar' => 'Laki-Laki',
                'alamat_pengajar' => 'Jl. Jeruk 2, No.27, Bengalon Utara, Kutai Timur, Kalimantan Timur',
                'tempat_lahir_pengajar' => 'Bangalon',
                'ttl_pengajar' => '1990-01-01',
                'jabatan_pengajar' => 'Guru Olahraga',
                'agama_pengajar' => 'Protestan',
                'suku_pengajar' => 'Dayak',
                'rt_rw_pengajar' => '002',
                'desa_kelurahan_pengajar' => 'Teluk Lingga',
                'kecamatan_kota_pengajar' => 'Kutai Timur',
                'kode_pos_pengajar' => 4423,
            ],
            [
                'id' => 6,
                'nip_pengajar' => 1232,
                'nama_pengajar' => 'Steven',
                'foto_pengajar' => 'foto_pengajar.png',
                'no_telp_pengajar'=>'08121312',
                'jenis_kelamin_pengajar' => 'Laki-Laki',
                'alamat_pengajar' => 'Jl. Anggur Merah 2, No.27, Samarinda Utara, Kutai Timur, Kalimantan Timur',
                'tempat_lahir_pengajar' => 'Bangalon',
                'ttl_pengajar' => '1990-01-01',
                'jabatan_pengajar' => 'Guru Olahraga',
                'agama_pengajar' => 'Protestan',
                'suku_pengajar' => 'Dayak',
                'rt_rw_pengajar' => '009',
                'desa_kelurahan_pengajar' => 'Teluk Lingga',
                'kecamatan_kota_pengajar' => 'Kutai Timur',
                'kode_pos_pengajar' => 87511,
            ],
            [
                'id' => 7,
                'nip_pengajar' => 13144,
                'nama_pengajar' => 'Rere',
                'foto_pengajar' => 'foto_pengajar.png',
                'no_telp_pengajar'=>'08121312',
                'jenis_kelamin_pengajar' => 'Laki-Laki',
                'alamat_pengajar' => 'Jl. Semangka 2, No.27, Bengalon Utara, Kutai Timur, Kalimantan Timur',
                'tempat_lahir_pengajar' => 'Bangalon',
                'ttl_pengajar' => '1990-01-01',
                'jabatan_pengajar' => 'Guru Olahraga',
                'agama_pengajar' => 'Protestan',
                'suku_pengajar' => 'Dayak',
                'rt_rw_pengajar' => '010',
                'desa_kelurahan_pengajar' => 'Teluk Lingga',
                'kecamatan_kota_pengajar' => 'Kutai Timur',
                'kode_pos_pengajar' => 463533,
            ],
            [
                'id' => 8,
                'nip_pengajar' => 23223,
                'nama_pengajar' => 'Iqbal Ramadhan',
                'foto_pengajar' => 'foto_pengajar.png',
                'no_telp_pengajar'=>'08121312',
                'jenis_kelamin_pengajar' => 'Laki-Laki',
                'alamat_pengajar' => 'Jl. Swal=embada 21, No.27, Bengalon Utara, Kutai Timur, Kalimantan Timur',
                'tempat_lahir_pengajar' => 'Bangalon',
                'ttl_pengajar' => '1990-01-01',
                'jabatan_pengajar' => 'Guru Olahraga',
                'agama_pengajar' => 'Protestan',
                'suku_pengajar' => 'Dayak',
                'rt_rw_pengajar' => '009',
                'desa_kelurahan_pengajar' => 'Teluk Lingga',
                'kecamatan_kota_pengajar' => 'Sangatta Utara',
                'kode_pos_pengajar' => 91312,
            ],
            [
                'id' => 9,
                'nip_pengajar' => 91287,
                'nama_pengajar' => 'Asep',
                'foto_pengajar' => 'foto_pengajar.png',
                'no_telp_pengajar'=>'08121312',
                'jenis_kelamin_pengajar' => 'Laki-Laki',
                'alamat_pengajar' => 'Jl. Manukwari2, No.27, Bengalon Utara, Kutai Timur, Kalimantan Timur',
                'tempat_lahir_pengajar' => 'Bangalon',
                'ttl_pengajar' => '1990-01-01',
                'jabatan_pengajar' => 'Guru Bahas Indoneisa',
                'agama_pengajar' => 'Protestan',
                'suku_pengajar' => 'Dayak',
                'rt_rw_pengajar' => '009',
                'desa_kelurahan_pengajar' => 'Teluk Lingga',
                'kecamatan_kota_pengajar' => 'Sangatta Utara',
                'kode_pos_pengajar' => 56743,
            ],
            [
                'id' => 10,
                'nip_pengajar' => 3122,
                'nama_pengajar' => 'Kiki',
                'foto_pengajar' => 'foto_pengajar.png',
                'no_telp_pengajar'=>'08121312',
                'jenis_kelamin_pengajar' => 'Laki-Laki',
                'alamat_pengajar' => 'Jl. Anggur 21, No.27, Bengalon Utara, Kutai Timur, Kalimantan Timur',
                'tempat_lahir_pengajar' => 'Bangalon',
                'ttl_pengajar' => '1990-01-01',
                'jabatan_pengajar' => 'Guru Olahraga',
                'agama_pengajar' => 'Protestan',
                'suku_pengajar' => 'Dayak',
                'rt_rw_pengajar' => '009',
                'desa_kelurahan_pengajar' => 'Singa Gembara',
                'kecamatan_kota_pengajar' => 'Sangatta Utara',
                'kode_pos_pengajar' => 9324,
            ],
        ]);
    }
}
